server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #false代表注册中心eureka，true代表服务提供方-providers
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: registry
  cloud:
    config:



management:
  endpoints:
    web:
      exposure:
        include: "*"
