server:
  port: 8764

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: order-server

management:
  endpoints:
    web:
      exposure:
        include: "*"